# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/ui_mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuFormat = QtGui.QMenu(self.menubar)
        self.menuFormat.setObjectName(_fromUtf8("menuFormat"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.openFileAction = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFileAction.setIcon(icon)
        self.openFileAction.setObjectName(_fromUtf8("openFileAction"))
        self.saveFileAction = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveFileAction.setIcon(icon1)
        self.saveFileAction.setObjectName(_fromUtf8("saveFileAction"))
        self.saveFileAsAction = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/save-as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveFileAsAction.setIcon(icon2)
        self.saveFileAsAction.setObjectName(_fromUtf8("saveFileAsAction"))
        self.exportHtmlAction = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/web.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportHtmlAction.setIcon(icon3)
        self.exportHtmlAction.setObjectName(_fromUtf8("exportHtmlAction"))
        self.closeAction = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/quit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAction.setIcon(icon4)
        self.closeAction.setObjectName(_fromUtf8("closeAction"))
        self.previewModeAction = QtGui.QAction(MainWindow)
        self.previewModeAction.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/preview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previewModeAction.setIcon(icon5)
        self.previewModeAction.setObjectName(_fromUtf8("previewModeAction"))
        self.boldFmtAction = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/bold.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boldFmtAction.setIcon(icon6)
        self.boldFmtAction.setObjectName(_fromUtf8("boldFmtAction"))
        self.italicFmtAction = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/italic.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.italicFmtAction.setIcon(icon7)
        self.italicFmtAction.setObjectName(_fromUtf8("italicFmtAction"))
        self.codeFmtAction = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/code.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.codeFmtAction.setIcon(icon8)
        self.codeFmtAction.setObjectName(_fromUtf8("codeFmtAction"))
        self.ulistFmtAction = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/bullet.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ulistFmtAction.setIcon(icon9)
        self.ulistFmtAction.setObjectName(_fromUtf8("ulistFmtAction"))
        self.olistFmtAction = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/number.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.olistFmtAction.setIcon(icon10)
        self.olistFmtAction.setObjectName(_fromUtf8("olistFmtAction"))
        self.linkFmtAction = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/link.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.linkFmtAction.setIcon(icon11)
        self.linkFmtAction.setObjectName(_fromUtf8("linkFmtAction"))
        self.imageFmtAction = QtGui.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imageFmtAction.setIcon(icon12)
        self.imageFmtAction.setObjectName(_fromUtf8("imageFmtAction"))
        self.menu_File.addAction(self.openFileAction)
        self.menu_File.addAction(self.saveFileAction)
        self.menu_File.addAction(self.saveFileAsAction)
        self.menu_File.addAction(self.exportHtmlAction)
        self.menu_File.addAction(self.closeAction)
        self.menuView.addAction(self.previewModeAction)
        self.menuFormat.addAction(self.boldFmtAction)
        self.menuFormat.addAction(self.italicFmtAction)
        self.menuFormat.addAction(self.codeFmtAction)
        self.menuFormat.addAction(self.ulistFmtAction)
        self.menuFormat.addAction(self.olistFmtAction)
        self.menuFormat.addAction(self.linkFmtAction)
        self.menuFormat.addAction(self.imageFmtAction)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.toolBar.addAction(self.openFileAction)
        self.toolBar.addAction(self.saveFileAction)
        self.toolBar.addAction(self.saveFileAsAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.previewModeAction)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.boldFmtAction)
        self.toolBar.addAction(self.italicFmtAction)
        self.toolBar.addAction(self.ulistFmtAction)
        self.toolBar.addAction(self.olistFmtAction)
        self.toolBar.addAction(self.codeFmtAction)
        self.toolBar.addAction(self.linkFmtAction)
        self.toolBar.addAction(self.imageFmtAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Text Editor", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuFormat.setTitle(_translate("MainWindow", "Format", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.openFileAction.setText(_translate("MainWindow", "Open", None))
        self.openFileAction.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.saveFileAction.setText(_translate("MainWindow", "Save", None))
        self.saveFileAction.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.saveFileAsAction.setText(_translate("MainWindow", "Save As...", None))
        self.saveFileAsAction.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.exportHtmlAction.setText(_translate("MainWindow", "Export Html", None))
        self.closeAction.setText(_translate("MainWindow", "Quit", None))
        self.closeAction.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.previewModeAction.setText(_translate("MainWindow", "Preview Mode", None))
        self.boldFmtAction.setText(_translate("MainWindow", "Bold", None))
        self.boldFmtAction.setShortcut(_translate("MainWindow", "Ctrl+B", None))
        self.italicFmtAction.setText(_translate("MainWindow", "Italic", None))
        self.italicFmtAction.setShortcut(_translate("MainWindow", "Ctrl+I", None))
        self.codeFmtAction.setText(_translate("MainWindow", "Inline Code", None))
        self.ulistFmtAction.setText(_translate("MainWindow", "Unordered List", None))
        self.olistFmtAction.setText(_translate("MainWindow", "Ordered List", None))
        self.linkFmtAction.setText(_translate("MainWindow", "Insert Link", None))
        self.imageFmtAction.setText(_translate("MainWindow", "Insert Image", None))

import resources_rc
